# Generated by Django 6.0.2 on 2026-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('año_finalizacion', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
