<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-03-06 10:28
=======
# Generated by Django 5.2.11 on 2026-03-09 15:35
>>>>>>> 5f3ae44d9e6ece5b9db81cfaac1b3de8adf6f898

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 5f3ae44d9e6ece5b9db81cfaac1b3de8adf6f898
                ('titulo', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('año_finalizacion', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
