# Generated by Django 6.0.3 on 2026-03-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo_empleo', models.CharField(choices=[('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial'), ('CT', 'Contrato'), ('FR', 'Freelance')], max_length=2)),
                ('descripcion', models.TextField()),
                ('aptitudes', models.CharField(max_length=300)),
                ('metodo_solicitud', models.EmailField(max_length=254)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
