<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-09 00:20
=======
# Generated by Django 5.2.11 on 2026-03-09 15:35
>>>>>>> 5f3ae44d9e6ece5b9db81cfaac1b3de8adf6f898

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo_empleo', models.CharField(choices=[('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial'), ('CT', 'Contrato'), ('FR', 'Freelance')], max_length=2)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo_empleo', models.CharField(choices=[('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial'), ('CT', 'Contrato'), ('RM', 'remoto'), ('FR', 'Freelance')], max_length=2)),
>>>>>>> 5f3ae44d9e6ece5b9db81cfaac1b3de8adf6f898
                ('descripcion', models.TextField()),
                ('aptitudes', models.CharField(max_length=300)),
                ('metodo_solicitud', models.EmailField(max_length=254)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
>>>>>>> 5f3ae44d9e6ece5b9db81cfaac1b3de8adf6f898
            ],
        ),
    ]
