# Generated by Django 6.0.3 on 2026-03-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='fecha_fin',
            field=models.DateField(default='2026-04-09'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='fecha_inicio',
            field=models.DateField(default='2026-03-09'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='tipo_empleo',
            field=models.CharField(choices=[('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial'), ('CT', 'Contrato'), ('RM', 'remoto'), ('FR', 'Freelance')], max_length=2),
        ),
    ]
